#region Vendor and export

macro(export_vendor_if_applicable VENDOR)
    string(TOUPPER "${PROJECT_NAME}" _evia_project_upper)
    string(TOUPPER "${VENDOR}"       _evia_vendor_upper)

    set(${_evia_project_upper}_VENDORS_${_evia_vendor_upper} OFF)

    if(${VENDOR}_ADDED)
        get_target_property(_evia_header_sets ${VENDOR} INTERFACE_HEADER_SETS)
        set(_evia_file_set_args "")

        if(_evia_header_sets)
            foreach(_evia_fs IN LISTS _evia_header_sets)
                list(APPEND _evia_file_set_args FILE_SET ${_evia_fs} DESTINATION "${CMAKE_INSTALL_INCLUDEDIR}")
            endforeach()
        endif()

        get_target_property(_evia_cxx_modules ${VENDOR} INTERFACE_CXX_MODULE_SETS)
        if(_evia_cxx_modules)
            foreach(_evia_fs IN LISTS _evia_cxx_modules)
                list(APPEND _evia_file_set_args FILE_SET ${_evia_fs} DESTINATION "${CMAKE_INSTALL_INCLUDEDIR}")
            endforeach()
        endif()

        install(TARGETS ${VENDOR}
                EXPORT ${PROJECT_NAME}Targets
                ${_evia_file_set_args}
        )

        if(NOT _evia_file_set_args AND EXISTS "${${VENDOR}_SOURCE_DIR}/include")
            install(DIRECTORY "${${VENDOR}_SOURCE_DIR}/include/"
                    DESTINATION "${CMAKE_INSTALL_INCLUDEDIR}")
        endif()

        set(${_evia_project_upper}_VENDORS_${_evia_vendor_upper} ON)
    endif()

    unset(_evia_header_sets)
    unset(_evia_cxx_modules)
    unset(_evia_file_set_args)
    unset(_evia_fs)
    unset(_evia_project_upper)
    unset(_evia_vendor_upper)
endmacro()

macro(ensure_alias_target ACTUAL_TARGET ALIAS_NAME)
    if(TARGET ${ACTUAL_TARGET} AND NOT TARGET ${ALIAS_NAME})
        add_library(${ALIAS_NAME} ALIAS ${ACTUAL_TARGET})
    endif()
endmacro()

#endregion

#region Subdirectories

function(add_subdirectory_if OPTION PATH)
    if(${OPTION})
        add_subdirectory(${PATH})
    endif()
endfunction()

function(add_project_test TARGET_NAME)
    add_executable(${TARGET_NAME} ${ARGN})

    target_include_directories(${TARGET_NAME} PRIVATE ${PROJECT_SOURCE_DIR}/tests)
    target_link_libraries(${TARGET_NAME} PRIVATE ${PROJECT_NAME} GTest::gtest_main)

    if(TARGET ${PROJECT_NAME}CompilerFlags)
        target_link_libraries(${TARGET_NAME} PRIVATE ${PROJECT_NAME}CompilerFlags)
    endif()

    gtest_discover_tests(${TARGET_NAME})
endfunction()

#endregion

#region LLDB

# Store the path of the LLDB scripts for all dependencies globally
# This allows subprojects (like Hermes) to register their scripts
# and the top-level project (like Thoth) to see them.

# "This dep has a LLDB!!"
macro(register_lldb_script DEP_NAME)
    if(${DEP_NAME} STREQUAL ${PROJECT_NAME})
        set(_lldb_script_path "${CMAKE_CURRENT_SOURCE_DIR}/tools/lldb/${PROJECT_NAME}Lldb.py")
    else()
        set(_lldb_script_path "${${DEP_NAME}_SOURCE_DIR}/tools/lldb/${DEP_NAME}Lldb.py")
    endif()

    if(EXISTS ${_lldb_script_path})
        # store in global variable to ensure transitivity
        set_property(GLOBAL APPEND PROPERTY GLOBAL_LLDB_SCRIPTS "${_lldb_script_path}")
        message(STATUS "LLDB: Found and registered debugger script for ${DEP_NAME}")
    endif()
    unset(_lldb_script_path)
endmacro()

# Generate a single appended .lldbinit in build folder
macro(generate_lldbinit)
    # Only runs on the top level project, but it has the *Lldb.py from all children.
    if(PROJECT_IS_TOP_LEVEL)
        set(LLDBINIT_FILE "${CMAKE_BINARY_DIR}/.lldbinit")
        file(WRITE ${LLDBINIT_FILE} "# Auto-generated by CMake. Do not edit.\n")
        file(APPEND ${LLDBINIT_FILE} "settings set target.load-script-from-symbol-file true\n")

        get_property(_scripts GLOBAL PROPERTY GLOBAL_LLDB_SCRIPTS)

        foreach(SCRIPT ${_scripts})
            file(APPEND ${LLDBINIT_FILE} "command script import \"${SCRIPT}\"\n")
        endforeach()

        message(STATUS "LLDB: Generated .lldbinit at ${LLDBINIT_FILE}")
    endif()
endmacro()

#endregion